version: 2

jobs:
   build:
       docker:
           - image: alpine
       steps:
           - checkout
           - run:
               name: Echo Test
               command: echo "CircleCI EC2 Test"
   # EC2 に SSH 接続・デプロイを実行
   deploy:
       machine:
           image: circleci/classic:edge
       steps:
           - checkout
           - add_ssh_keys:
           - run: ssh ubuntu@3.112.34.148

workflows:
   version: 2
   build_and_deploy:
       jobs:
           - build
           - deploy:
               requires:
                   - build
               # master ブランチに push された場合のみ deploy
               filters:
                   branches:
                       only: master
